= AWS tools maven plugin

At the moment only supports upload of resources to S3 bucket.

== Usage

* Set up your preferred way of supplying AWS credentials
* Configure plugin in then pom
* Run `mvn aws-tools:upload`

For example, the minimal configuration below will upload file `background.jpg` into `castle-public` bucket. Credentials will bee looked in the `USER_HOME/.aws/credentials` file.

 <build>
 	<pluginManagement>
 		<plugins>
 			<plugin>
 				<groupId>org.deffer.maven</groupId>
 				<artifactId>aws-tools-maven-plugin</artifactId>
 				<version>1.1</version>
 				<extensions>true</extensions>
 				<configuration>
 					<source>background.jpg</source>
 					<bucketName>castle-public</bucketName>
 				</configuration>
 			</plugin>
 		</plugins>
 	</pluginManagement>
 </build>

To upload several files, use

 <configuration>
    <sources>
 	    <source>background.jpg</source>
 	    <source>tile.jpg</source>
    </sources>
 	<bucketName>castle-public</bucketName>
 </configuration>

== Description

Can upload 1 file, list of files, content of 1 folder, content on several folders into one `destination` (folder).

When uploading folder, only its content is uploaded (not the folder itself). With `recursive=true` it will include sub-folders (with their original names).
For example, with this directory layout

 my-app
 |-- pom.xml
 |-- assets.zip
 `-- ASSETS
     |-- castle.jpg
     |-- welcome.jpg
     `-- IMAGES
         |-- a.png
         `-- b.png

and this configuration

 <bucketName>castle-public</bucketName>
 <destination>data</destination>
 <sources>
    <source>assets.zip</source>
    <source>tile.jpg</source>
 </sources>

will result in next S3 structure

 data/assets.zip
 data/castle.jpg
 data/welcome.jpg
 data/IMAGES/a.png
 data/IMAGES/b.png


When uploading file or list of files, there is an option to add a `suffix` to each file name (ex. version)

When uploading single file, `destination` is treated as new file name.

Path to files/folders is relative to current working dir.

=== Limitations

Only one bucket and one destination folder can be configured per execution.

No metadata support. No ACL support.

Suffix only supported for files (single or list) but not in folders

== Configuration

[cols="1,1,2"]
.Parameters
|===
|Name |Required |Description

|bucketName
|yes
|name of the bucket in S3, ex. `my-public-bucket`

|credentialProvider
|no
|`env, java, file (default), instance or provided`. See below for description.

|source
|yes* (either source or sources)
|name of the single file to upload

|sources
|yes* (either source or sources)
|list of files/folders to upload

|destination
|no
|if only one source is defined, destination means new (S3) file name. otherwise its treated as name of "subfolder" in the bucket where files/folders will be copied to

|recursive
|no
|_default false_ when uploading folder, indicates whether inner folders should be uploaded to

|suffix
|no
|when uploading files (no folders), suffix is added to the end of destination filename. can be used as version.

|dryRun
|no
|_default false_ Skips the actual upload. Use it to test your configuration before running it.

|accessKey,
secretKey
|no
|required when credentialProvider is `provided`
|===

== Credentials options

== Examples
